version: ">= v0.16.0"

formatter: "markdown table"

content: |-
  # Terraform Cloud ACI Tenant Module

  Create and ACI Tenant for Cloud APIC in AWS User Account.

  ## Examples

  ### Example AWS Tenant

  ```hcl
  {{ include "./example/main.tf" }}
  ```

  {{ .Requirements }}

  {{ .Providers }}

  {{ .Inputs }}

  {{ .Outputs }}

  {{ .Resources }}

output:
  file: README.md
  mode: replace

sort:
  enabled: false
